### ISSUE TITLE
Stream graphic does not match cells

### ISSUE THREAD

**Issue by rlfrahm** [nrem/pewi#105]
![pewi_watershed_old](https://cloud.githubusercontent.com/assets/5338740/8441584/e60a2eb0-1f3e-11e5-8937-7cf7e168a4dd.png)
![pewi_watershed_new](https://cloud.githubusercontent.com/assets/5338740/8441591/e82cba64-1f3e-11e5-807a-5ba082a68099.PNG)

**Comment by carriec** [comment]
The second of the two images is from PEWI on 6/30/2015, with the first of the two images taken before the most recent release.  Problem:  The stream does not line up the same from one image to another, with the newer (second) image being incorrect.
Details: The upper left origin of the stream is in grid cell coordinate 7,10 in the old screen capture and 7,11 in the new (if both streams originated from the same grid cell, they would both be starting from the third-from-the-top wetland).  You can also see how the alignment issue continues downstream.  I am not sure how the issue originated.  Both images were screen captures taken from PEWI in a Chrome browser, set to 100% zoom.  I tried zooming in/out of the new image to no avail.  Presumably the stream should be "locked" to certain coordinates designated as "stream" cells, regardless of the size of the watershed or the browser zoom.

**Comment by tomtinkerer** [comment]
Problem fixed in v3.0
