### ISSUE TITLE
Grassland Points and Percentage addition

### ISSUE THREAD

**Issue by tomtinkerer** [nrem/pewi#119]
Need to add "grassland points" and "grassland percentage" to the code, where a 'grassland' is defined as either (1) perennial bioenergy, (2) prairie, or (3) rotational grazing.

The following code additions will need to be made:
- add the following variables
       - grasslandArea
       - grasslandPercent
       - grasslandGindex
- add the following functions
       - setGrasslandArea
       - setGrasslandPercent
- add if/else statement to calculate grasslandGindex value

This covers lines 85 and 86 of the Data Dictionary

**Comment by rlfrahm** [comment]
@tomtinkerer, do these values need to be printed to the results modal?

**Comment by tomtinkerer** [comment]
For now I thought not, will ask Carrie
