### ISSUE TITLE
Improvement maps hover indicators display wrong numbers

### ISSUE THREAD

**Issue by rlfrahm** [nrem/pewi#29]
The phosphorus map should display the P-index score for the cell.

The erosion map should display the gross erosion for the cell.

The nitrate map should show the nitrate percent contribution for each sub-watershed.

**Comment by rlfrahm** [comment]
The hover numbers appear to be correct according to the data that is used to generate the maps and the legend.

**Comment by carriec** [comment]
The P and erosion hover display numbers on the Maps page are still wrong, in spite of the rlfrahm comment on April 1 to the contrary.  
Phosphorus Risk Assessment:  When hovering, display the numerical value of the "Phosphorus Index" in lb/ac for a grid cell (e.g. 1.7 lb/ac), not the categorical value ("Very Low", etc.).  
Gross Erosion:  When hovering, display the "Gross Erosion per Unit Area" in tons/ac for a grid cell (e.g. 14.8 tons/ac). The only values displayed now are only the incorrect numbers 1, 2, 3, 4, 5 (without units), yet these whole numbers do not correspond to the amount of gross erosion per unit area.  Please ask questions if further clarification is required.

**Comment by rlfrahm** [comment]
@carriec can you please take a look at #102 and advise whether the numbers are correct now?
