### ISSUE TITLE
Results page needs to match design document

### ISSUE THREAD

**Issue by rlfrahm** [nrem/pewi#40]
The results popup should match the original design.

![screen shot 2014-06-18 at 8 49 09 am](https://cloud.githubusercontent.com/assets/5338740/3314344/ce593f7c-f6ef-11e3-9e0a-46feb005b7ff.png)

**Comment by carriec** [comment]
![image](https://cloud.githubusercontent.com/assets/6509455/6626448/9b07085a-c8c4-11e4-983b-98a09857bccf.png)

Here is a screen capture of the new design template (20140905_DRAFT_PEWI_v_2.0_Print_Results_Template)
