### ISSUE TITLE
Update code to reflect changes to data elements and calculations

### ISSUE THREAD

**Issue by carriec** [nrem/pewi#50]
Since late spring, several calculations have been added and changed in the data dictionary due to the thesis review process.  These changes need to be updated in the code, so that the model will calculate correctly.  A new version of the data dictionary was created to reflect post-thesis status of PE/WI: 20140814_DRAFT_PEWI_v_2.0_Data_Dictionary_CC

These include the addition of new data elements and modification of calculation of existing elements (both red status), the removal of original data elements (orange status), and name changes (yellow status).  As you update these elements in the code, please change the status in the dictionary to reflect that the task has been done (green for complete, black for deprecate).  Also, for orange status items, we expect to potentially re-add these to the model in future versions.  Is it possible to comment these lines out with a description of why they are commented out (or really any other solution will work, just so that someone does not have to redo this work later)?

Although this issue relates to issue #45, that issue specifically addressed data dictionary changes that would result in display changes (the interface), whereas this issue focuses on data dictionary changes that would result in changes to the calculations/data elements themselves.  Although it probably goes without saying, these calculation updates will require further testing of the model to identify potential calculation errors in the code.

**Comment by rlfrahm** [comment]
@carriec 

Can you please outline specifically the changes that need to take place?

**Comment by tomtinkerer** [comment]
Updated have been fully implemented
