### ISSUE TITLE
Clicking freezes & dragging produces no results when replacing hay with hay

### ISSUE THREAD

**Issue by rlfrahm** [nrem/pewi#92]
Currently, if the user tries to replace Hay with Hay, the click freezes, and dragging the cursor around produces no results. Replacing Hay with Corn, however, then allows the user to drag the cursor around and replace multiple blocks with Corn

**Comment by tomtinkerer** [comment]
This Issue still exists for v2.0, but has been fixed in v3.0. Ignoring for the sake of not duplicating work.
